# Generated by Django 4.1.2 on 2022-10-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
