# Generated by Django 4.1.2 on 2022-10-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_todo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_image',
            new_name='image',
        ),
    ]
